### ISSUE TITLE
print function seems borked with single type roc

### ISSUE THREAD

**Issue by jlangaa** [jlangaa/bouldr#7]
Even running print(single) breaks on the vignette example. wtf!

**Comment by jlangaa** [comment]
Could you please show us the error?

**Comment by jlangaa** [comment]
Sure!

`

> print(single) Outcome var:	 Outcome  Error in rhs[[2]] : object of type 'symbol' is not subsettable
--
 
> | >
>

`

**Comment by bellete** [comment]
The problem is with this line in print:

`
cat("Predictor var:\t", rhs[[2]][[2]], "\n")
`

**Comment by jlangaa** [comment]
it seems that in the single-predictor ROC case, rhs is not a list, and therefore cannot be subsetted with [[ ]]. Might need to include some if ( ) statement logic to account for the single-predictor case.

**Comment by bellete** [comment]
![IMG_3498](https://user-images.githubusercontent.com/54329480/110031809-5c31ad00-7d05-11eb-972a-366673170c43.JPG)

I tried to fix the error. Is this how you want the print to be like?

**Comment by bellete** [comment]
<img width="756" alt="Screen Shot 2021-03-04 at 16 22 33" src="https://user-images.githubusercontent.com/54329480/110032217-e1b55d00-7d05-11eb-803e-ab651078b119.png">

This part looks good btw

**Comment by bellete** [comment]
It can only print formulas with one factor. Need more fix.

**Comment by bellete** [comment]
(Sorry. I click the wrong button.) It can only print one-factor-formula after the fix. 

`
Error in cat("Predictor var:\t", rhs, "\n") : argument 2 (type 'language') cannot be handled by 'c
`
